Cloudless: cloudless::message Struct Reference
cloudless::message Struct Reference
A message container for elements which 0MQ messages.
#include <message.hpp>
Public Member Functions
message ()
A default constructor.
message (const std::string &data)
A constructor that takes a std::string.
message (const void *p, size_t size)
A constructor that takes a char array and its size.
message (const element &elem)
A constructor that takes an element.
element tail ()
Get the message at the bottom of the stack.
message & push_tail (const element &elem)
Push an element at the buttom of the stack.
message & push_tail (const std::string &data)
Push a std::string at the bottom of the stack.
message & push_tail (const void *p, size_t size)
Push a char array at the bottom of the stack.
element pop_tail ()
Pop the message at the bottom of the stack.
element head ()
Get the message at the bottom of the stack.
message & push_head (const element &elem)
Push an element at the top of the stack.
message & push_head (const std::string &data)
Push a std::string at the bottom of the stack.
message & push_head (const void *p, size_t size)
Push a char array at the bottom of the stack.
element pop_head ()
Pop the message at the bottom of the stack.
size_t size () const throw ()
Get the size of the messages container.
void clear () throw ()
Empty the messages container.
element operator[] (size_t idx) const
Access elements in the container by index.
std::deque< element > * operator-> ()
Detailed Description
A message container for elements which 0MQ messages.
Definition at line 45 of file message.hpp.
Constructor & Destructor Documentation
cloudless::message::message () [inline]
A default constructor.
Definition at line 51 of file message.hpp.
{}
cloudless::message::message (const std::string & data)
A constructor that takes a std::string.
Parameters:
data a std::string for data to be put as a message in a container.
Definition at line 36 of file message.cpp.
References push_tail().
    {
        push_tail(data);
    }
cloudless::message::message (const void * p, size_t size)
A constructor that takes a char array and its size.
Parameters:
p a pointer to a char array.
size the size of the char array.
Definition at line 41 of file message.cpp.
References push_tail().
    {
        push_tail(p, size);
    }
cloudless::message::message (const element & elem)
A constructor that takes an element.
Parameters:
elem an element that wraps a 0MQ message.
Definition at line 46 of file message.cpp.
References push_tail().
    {
        push_tail(elem);
    }
Member Function Documentation
void cloudless::message::clear () throw ()
Empty the messages container.
Definition at line 145 of file message.cpp.
    {
        _M_elements.clear();
    }
element cloudless::message::head ()
Get the message at the bottom of the stack.
Returns:
an element.
Definition at line 94 of file message.cpp.
    {
        if (!_M_elements.empty())
            return _M_elements.front();
        if (_M_element.get() == NULL)
            _M_element.reset(new detail::zmessage);
        return _M_element;
    }
std::deque< element > * cloudless::message::operator-> ()
Definition at line 151 of file message.cpp.
    {
        return &_M_elements;
    }
element cloudless::message::operator[] (size_t idx) const
Access elements in the container by index.
Parameters:
idx the index of the element.
Returns:
an element.
Definition at line 157 of file message.cpp.
    {
        return _M_elements.at(idx);
    }
element cloudless::message::pop_head ()
Pop the message at the bottom of the stack.
Returns:
an element.
Definition at line 126 of file message.cpp.
    {
        if (!_M_elements.empty() && !_M_elements.front()->size())
            _M_elements.pop_front();
        element ret = _M_elements.front();
        _M_elements.pop_front();
        return ret;
    }
element cloudless::message::pop_tail ()
Pop the message at the bottom of the stack.
Returns:
an element.
Definition at line 84 of file message.cpp.
    {
        element ret = _M_elements.back();
        _M_elements.pop_back();
        return ret;
    }
message & cloudless::message::push_head (const element & elem)
Push an element at the top of the stack.
Parameters:
elem an element that wraps a 0MQ message.
Definition at line 106 of file message.cpp.
    {
        _M_elements.push_front(elem);
        return *this;
    }
message & cloudless::message::push_head (const std::string & data)
Push a std::string at the bottom of the stack.
Parameters:
data a std::string data that will be wrapped as an element internally.
Definition at line 114 of file message.cpp.
References push_head().
    {
        return push_head(element(data));
    }
message & cloudless::message::push_head (const void * p, size_t size)
Push a char array at the bottom of the stack.
Parameters:
p a pointer to a char array.
size the size of the char array.
Definition at line 120 of file message.cpp.
References push_head().
    {
        return push_head(element(p, size));
    }
message & cloudless::message::push_tail (const element & elem)
Push an element at the buttom of the stack.
Parameters:
elem an element that wraps a 0MQ message.
Definition at line 64 of file message.cpp.
    {
        _M_elements.push_back(elem);
        return *this;
    }
message & cloudless::message::push_tail (const std::string & data)
Push a std::string at the bottom of the stack.
Parameters:
data a std::string data that will be wrapped as an element internally.
Definition at line 72 of file message.cpp.
References push_tail().
    {
        return push_tail(element(data));
    }
message & cloudless::message::push_tail (const void * p, size_t size)
Push a char array at the bottom of the stack.
Parameters:
p a pointer to a char array.
size the size of the char array.
Definition at line 78 of file message.cpp.
References push_tail().
    {
        return push_tail(element(p, size));
    }
size_t cloudless::message::size () const throw ()
Get the size of the messages container.
Returns:
the size of the container.
Definition at line 139 of file message.cpp.
    {
        return _M_elements.size();
    }
element cloudless::message::tail ()
Get the message at the bottom of the stack.
Returns:
an element.
Definition at line 52 of file message.cpp.
    {
        if (!_M_elements.empty())
            return _M_elements.back();
        if (_M_element.get() == NULL)
            _M_element.reset(new detail::zmessage);
        return _M_element;
    }
The documentation for this struct was generated from the following files:
cloudless/message.hpp (b2af4c3103aead4129eb1d20a009a9918172426a)
cloudless/message.cpp (b2af4c3103aead4129eb1d20a009a9918172426a)