#!/bin/sh

command -v libtool >/dev/null 2>&1
if test $? -ne 0; then
	echo "bootstrap: error: could not find libtool.  libtool is required to run bootstrap." 1>&2
	exit 1
fi

command -v autoreconf >/dev/null 2>&1
if test $? -ne 0; then
	echo "bootstrap: error: could not find autoreconf.  autoconf and automake are required to run bootstrap." 1>&2
	exit 1
fi

if test ! -d m4; then
	echo "bootstrap: error: could not find directory: m4." 1>&2
	exit 1
fi

if test ! -d config; then
	mkdir config

	if test $? -ne 0; then
		echo "bootstrap: error: could not create directory: config." 1>&2
		exit 1
	fi
fi

autoreconf -vif
if test $? -ne 0; then
	echo "bootstrap: error: autoreconf exited with status $?" 1>&2
	exit 1
fi
