Cloudless: cloudless::detail::zsocket Struct Reference
cloudless::detail::zsocket Struct Reference
A wrapper structure around 0MQ low level socket interface.
#include <zsocket.hpp>
Public Member Functions
zsocket (zcontext &context, int type)
A constructor that takes a zcontext and a socket type.
virtual ~zsocket ()
A destructor to close the 0MQ socket.
void close ()
A function to close the 0MQ socket.
void setsockopt (int option, const void *optval, size_t optvallen)
Set 0MQ socket options.
void getsockopt (int option, void *optval, size_t *optvallen) const
Get 0MQ socket options.
void bind (const char *addr)
Bind a socket to a specific address.
void connect (const char *addr)
Connect a socket to a specific address.
bool sendmsg (zmessage &msg, int flags=0)
Send a message.
bool recvmsg (zmessage &msg, int flags=0)
Receive a message.
uint64_t affinity () const
Get socket's affinity.
std::string identity () const
Get socket's identity.
int rate () const
Get socket's multicast data rate.
int recovery_ivl () const
Get multicast recovery interval.
int send_buffer () const
Get kernel transmit buffer size.
int recv_buffer () const
Get kernel receive buffer size.
bool recv_more () const
Check if there are more message parts to follow while receiving a message.
socket_t fd () const
Get the file descriptor associated with the socket.
bool can_send () const
Check if a message can be sent without blocking.
bool can_recv () const
Check if a message can be received without blocking.
int type () const
Get this socket's type.
int linger () const
Get the linger period for socket shutdown.
int reconnect_ivl () const
Get reconnection interval.
int reconnect_ivl_max () const
Get the maximum reconnection interval.
int backlog () const
Get the maximum length of the queue of outstanding connections.
int64_t max_msg_size () const
Get maximum acceptable inbound message size.
int send_hwm () const
Get high water mark for outbound messages.
int recv_hwm () const
Get high water mark for inbound messages.
int multicast_hops () const
Get maximum network hops for multicast packets.
int send_timeout () const
Get maximum time before a send operation times out.
int recv_timeout () const
Get maximum time before a receive operation times out.
bool ipv4_only () const
Check if this socket will operate only on IPv4.
zsocket & affinity (uint64_t affinity)
Set socket's affinity.
zsocket & identity (const std::string &identity)
Set socket's identity.
zsocket & rate (int rate)
Set socket's multicast data rate.
zsocket & recovery_ivl (int ivl)
Set multicast recovery interval.
zsocket & send_buffer (int size)
Set kernel transmit buffer size.
zsocket & recv_buffer (int size)
Set kernel receive buffer size.
zsocket & linger (int linger)
Set the linger period for socket shutdown.
zsocket & reconnect_ivl (int ivl, int max=0)
Set reconnection interval.
zsocket & backlog (int backlog)
Set the maximum length of the queue of outstanding connections.
zsocket & max_msg_size (int64_t max_size)
Set maximum acceptable inbound message size.
zsocket & hwm (int hwm)
Set high water mark for both inbound and outbound messages.
zsocket & send_hwm (int hwm)
Set high water mark for outbound messages.
zsocket & recv_hwm (int hwm)
Set high water mark for inbound messages.
zsocket & multicast_hops (int hops)
Set maximum network hops for multicast packets.
zsocket & send_timeout (int timeout)
Set maximum time before a send operation times out.
zsocket & recv_timeout (int timeout)
Set maximum time before a receive operation times out.
zsocket & ipv4_only (bool ipv4_only)
Set this socket to operate only on IPv4.
zsocket & subscribe (const std::string &topic)
Subscribe to a topic on a SUB socket.
zsocket & unsubscribe (const std::string &topic)
Unsubscribe from a topic on a SUB socket.
operator void * () const throw ()
Expose internal 0MQ's socket pointer.
Detailed Description
A wrapper structure around 0MQ low level socket interface.
Definition at line 70 of file zsocket.hpp.
Constructor & Destructor Documentation
cloudless::detail::zsocket::zsocket (zcontext & context, int type)
A constructor that takes a zcontext and a socket type.
Parameters:
context a zcontext reference.
type a socket type from cloudless::socket_type
Definition at line 47 of file zsocket.cpp.
                                                :
        _M_recvtimeo(-1), _M_sendtimeo(-1)
    {
        _Mp_socket = zmq_socket(context, type);
        if (_Mp_socket == NULL)
            raise(zexception);
    }
cloudless::detail::zsocket::~zsocket () [virtual]
A destructor to close the 0MQ socket.
This destructor is essentially the same as close() but does not check for errors from zmq_close() as destructors must not raise exceptions.
Definition at line 56 of file zsocket.cpp.
    {
        if (_Mp_socket == NULL)
            return;
        zmq_close(_Mp_socket);
        _Mp_socket = NULL;
    }
Member Function Documentation
uint64_t cloudless::detail::zsocket::affinity () const
Get socket's affinity.
See 0MQ's documentation.
Returns:
the affinity of this socket.
Definition at line 157 of file zsocket.cpp.
References _M_getsockopt.
    {
        uint64_t affinity;
        _M_getsockopt(ZMQ_AFFINITY, affinity);
        return affinity;
    }
zsocket & cloudless::detail::zsocket::affinity (uint64_t affinity)
Set socket's affinity.
See 0MQ's documentation.
Parameters:
affinity the affinity of this socket.
Definition at line 382 of file zsocket.cpp.
References _M_setsockopt.
    {
        _M_setsockopt(ZMQ_AFFINITY, affinity);
        return *this;
    }
int cloudless::detail::zsocket::backlog () const
Get the maximum length of the queue of outstanding connections.
See 0MQ's documentation.
Returns:
the number of connections.
Definition at line 282 of file zsocket.cpp.
References _M_getsockopt.
    {
        int backlog;
        _M_getsockopt(ZMQ_BACKLOG, backlog);
        return backlog;
    }
zsocket & cloudless::detail::zsocket::backlog (int backlog)
Set the maximum length of the queue of outstanding connections.
See 0MQ's documentation.
Parameters:
backlog the number of connections.
Definition at line 452 of file zsocket.cpp.
References _M_setsockopt.
    {
        _M_setsockopt(ZMQ_BACKLOG, backlog);
        return *this;
    }
void cloudless::detail::zsocket::bind (const char * addr)
Bind a socket to a specific address.
Parameters:
addr a 0MQ address. See to 0MQ's documentation.
Definition at line 101 of file zsocket.cpp.
    {
        int rc = zmq_bind(_Mp_socket, addr);
        if (rc == -1)
            raise(zexception);
    }
bool cloudless::detail::zsocket::can_recv () const
Check if a message can be received without blocking.
See 0MQ's documentation.
Returns:
true or false.
Definition at line 240 of file zsocket.cpp.
    {
        return _M_get_events() & ZMQ_POLLIN;
    }
bool cloudless::detail::zsocket::can_send () const
Check if a message can be sent without blocking.
See 0MQ's documentation.
Returns:
true or false.
Definition at line 234 of file zsocket.cpp.
    {
        return _M_get_events() & ZMQ_POLLOUT;
    }
void cloudless::detail::zsocket::close ()
A function to close the 0MQ socket.
Definition at line 67 of file zsocket.cpp.
    {
        if (_Mp_socket == NULL)
            return;
        int rc = zmq_close(_Mp_socket);
        if (rc == -1)
            raise(zexception);
        _Mp_socket = NULL;
    }
void cloudless::detail::zsocket::connect (const char * addr)
Connect a socket to a specific address.
Parameters:
addr a 0MQ address. See to 0MQ's documentation.
Definition at line 110 of file zsocket.cpp.
    {
        int rc = zmq_connect(_Mp_socket, addr);
        if (rc == -1)
            raise(zexception);
    }
socket_t cloudless::detail::zsocket::fd () const
Get the file descriptor associated with the socket.
See 0MQ's documentation.
Returns:
socket's FD. Either int on POSIX systems, or SOCKET on Windows.
Definition at line 225 of file zsocket.cpp.
References _M_getsockopt.
    {
        socket_t fd;
        _M_getsockopt(ZMQ_FD, fd);
        return fd;
    }
void cloudless::detail::zsocket::getsockopt (int option, void * optval, size_t * optvallen) const
Get 0MQ socket options.
Parameters:
option a 0MQ socket option. See to 0MQ's documentation.
optval a pointer to a value container to be assigned to.
optvallen the size of the container of the value.
Definition at line 91 of file zsocket.cpp.
    {
        int rc = zmq_getsockopt(_Mp_socket, option, optval, optvallen);
        if (rc == -1)
            raise(zexception);
    }
zsocket & cloudless::detail::zsocket::hwm (int hwm)
Set high water mark for both inbound and outbound messages.
See 0MQ's documentation.
Parameters:
hwm high water mark for inbound and outbound messages.
Definition at line 468 of file zsocket.cpp.
References _M_setsockopt.
    {
#if ZMQ_VERSION_MAJOR == 3
        _M_setsockopt(ZMQ_SNDHWM, hwm);
        _M_setsockopt(ZMQ_RCVHWM, hwm);
#elif ZMQ_VERSION_MAJOR == 2
        uint64v hwm_ = hwm;
        _M_setsockopt(ZMQ_HWM, hwm_);
#endif
        return *this;
    }
std::string cloudless::detail::zsocket::identity () const
Get socket's identity.
See 0MQ's documentation.
Returns:
the socket identity in a std::string representation.
Definition at line 166 of file zsocket.cpp.
References _M_getsockopt.
    {
        char id[256];
        _M_getsockopt(ZMQ_IDENTITY, id);
        return std::string(id, optvallen_);
    }
zsocket & cloudless::detail::zsocket::identity (const std::string & identity)
Set socket's identity.
See 0MQ's documentation.
Parameters:
identity the socket identity in a std::string representation.
Definition at line 389 of file zsocket.cpp.
References setsockopt().
    {
        setsockopt(ZMQ_IDENTITY, identity.c_str(), identity.size());
        return *this;
    }
bool cloudless::detail::zsocket::ipv4_only () const
Check if this socket will operate only on IPv4.
See 0MQ's documentation.
Returns:
true or false.
Definition at line 369 of file zsocket.cpp.
References _M_getsockopt.
    {
#if ZMQ_VERSION_MAJOR == 3
        int ipv4;
        _M_getsockopt(ZMQ_IPV4ONLY, ipv4);
        return ipv4;
#elif ZMQ_VERSION_MAJOR == 2
        return true;
#endif
    }
zsocket & cloudless::detail::zsocket::ipv4_only (bool ipv4_only)
Set this socket to operate only on IPv4.
See 0MQ's documentation.
Parameters:
ipv4_only true or false.
Definition at line 541 of file zsocket.cpp.
References _M_setsockopt, and ipv4_only().
    {
#if ZMQ_VERSION_MAJOR == 3
        int ipv4 = ipv4_only;
        _M_setsockopt(ZMQ_IPV4ONLY, ipv4);
#endif
        return *this;
    }
int cloudless::detail::zsocket::linger () const
Get the linger period for socket shutdown.
See 0MQ's documentation.
Returns:
the linger period in milliseconds. -1 means infinite.
Definition at line 255 of file zsocket.cpp.
References _M_getsockopt.
    {
        int linger;
        _M_getsockopt(ZMQ_LINGER, linger);
        return linger;
    }
zsocket & cloudless::detail::zsocket::linger (int linger)
Set the linger period for socket shutdown.
See 0MQ's documentation.
Parameters:
linger the linger period in milliseconds. -1 means infinite.
Definition at line 437 of file zsocket.cpp.
References _M_setsockopt.
    {
        _M_setsockopt(ZMQ_LINGER, linger);
        return *this;
    }
int64_t cloudless::detail::zsocket::max_msg_size () const
Get maximum acceptable inbound message size.
See 0MQ's documentation.
Returns:
maximum acceptable inbound message size in bytes. Value of -1 means no limit.
Definition at line 291 of file zsocket.cpp.
References _M_getsockopt.
    {
        int64_t mms = -1;
#if ZMQ_VERSION_MAJOR == 3
        _M_getsockopt(ZMQ_MAXMSGSIZE, mms);
#endif
        return mms;
    }
zsocket & cloudless::detail::zsocket::max_msg_size (int64_t max_size)
Set maximum acceptable inbound message size.
See 0MQ's documentation.
Parameters:
max_size maximum acceptable inbound message size in bytes. Value of -1 means no limit.
Definition at line 459 of file zsocket.cpp.
References _M_setsockopt.
    {
#if ZMQ_VERSION_MAJOR == 3
        _M_setsockopt(ZMQ_MAXMSGSIZE, max_size);
#endif
        return *this;
    }
int cloudless::detail::zsocket::multicast_hops () const
Get maximum network hops for multicast packets.
See 0MQ's documentation.
Returns:
maximum network hops.
Definition at line 330 of file zsocket.cpp.
References _M_getsockopt.
    {
#if ZMQ_VERSION_MAJOR == 3
        int hops;
        _M_getsockopt(ZMQ_MULTICAST_HOPS, hops);
        return hops;
#elif ZMQ_VERSION_MAJOR == 2
        return -1;
#endif
    }
zsocket & cloudless::detail::zsocket::multicast_hops (int hops)
Set maximum network hops for multicast packets.
See 0MQ's documentation.
Parameters:
hops maximum network hops.
Definition at line 510 of file zsocket.cpp.
References _M_setsockopt.
    {
#if ZMQ_VERSION_MAJOR == 3
        _M_setsockopt(ZMQ_MULTICAST_HOPS, hops);
#endif
        return *this;
    }
cloudless::detail::zsocket::operator void * () const throw ()
Expose internal 0MQ's socket pointer.
Returns:
0MQ's socket void pointer.
Definition at line 571 of file zsocket.cpp.
    {
        return _Mp_socket;
    }
int cloudless::detail::zsocket::rate () const
Get socket's multicast data rate.
See 0MQ's documentation.
Returns:
the socket's multicast data rate in kilobits per second.
Definition at line 175 of file zsocket.cpp.
References _M_getsockopt.
    {
        int64v rate;
        _M_getsockopt(ZMQ_RATE, rate);
        return rate;
    }
zsocket & cloudless::detail::zsocket::rate (int rate)
Set socket's multicast data rate.
See 0MQ's documentation.
Parameters:
rate the socket's multicast data rate in kilobits per second.
Definition at line 396 of file zsocket.cpp.
References _M_setsockopt, and rate().
    {
        int64v rate_ = rate;
        _M_setsockopt(ZMQ_RATE, rate_);
        return *this;
    }
int cloudless::detail::zsocket::reconnect_ivl () const
Get reconnection interval.
See 0MQ's documentation.
Returns:
the reconnection interval in milliseconds.
Definition at line 264 of file zsocket.cpp.
References _M_getsockopt.
    {
        int ivl;
        _M_getsockopt(ZMQ_RECONNECT_IVL, ivl);
        return ivl;
    }
zsocket & cloudless::detail::zsocket::reconnect_ivl (int ivl, int max = 0)
Set reconnection interval.
See 0MQ's documentation.
Parameters:
ivl the reconnection interval in milliseconds.
max the maximum reconnection interval in milliseconds.
Definition at line 444 of file zsocket.cpp.
References _M_setsockopt.
    {
        _M_setsockopt(ZMQ_RECONNECT_IVL, ivl);
        _M_setsockopt(ZMQ_RECONNECT_IVL_MAX, max);
        return *this;
    }
int cloudless::detail::zsocket::reconnect_ivl_max () const
Get the maximum reconnection interval.
See 0MQ's documentation.
Returns:
the maximum reconnection interval in milliseconds.
Definition at line 273 of file zsocket.cpp.
References _M_getsockopt.
    {
        int ivl_max;
        _M_getsockopt(ZMQ_RECONNECT_IVL_MAX, ivl_max);
        return ivl_max;
    }
int cloudless::detail::zsocket::recovery_ivl () const
Get multicast recovery interval.
See 0MQ's documentation.
Returns:
the socket's multicast recovery interval.
Definition at line 184 of file zsocket.cpp.
References _M_getsockopt.
    {
#if ZMQ_VERSION_MAJOR == 3
        int opt = ZMQ_RECOVERY_IVL;
#elif ZMQ_VERSION_MAJOR == 2
        int opt = ZMQ_RECOVERY_IVL_MSEC;
#endif
        int64v recovery_ivl;
        _M_getsockopt(opt, recovery_ivl);
        return recovery_ivl;
    }
zsocket & cloudless::detail::zsocket::recovery_ivl (int ivl)
Set multicast recovery interval.
See 0MQ's documentation.
Parameters:
ivl the socket's multicast recovery interval.
Definition at line 405 of file zsocket.cpp.
References _M_setsockopt.
    {
#if ZMQ_VERSION_MAJOR == 3
        int opt = ZMQ_RECOVERY_IVL;
#elif ZMQ_VERSION_MAJOR == 2
        int opt = ZMQ_RECOVERY_IVL_MSEC;
#endif
        int64v ivl_ = ivl;
        _M_setsockopt(opt, ivl_);
        return *this;
    }
int cloudless::detail::zsocket::recv_buffer () const
Get kernel receive buffer size.
See 0MQ's documentation.
Returns:
the receive buffer size of the kernel.
Definition at line 207 of file zsocket.cpp.
References _M_getsockopt.
    {
        uint64v buffer;
        _M_getsockopt(ZMQ_RCVBUF, buffer);
        return buffer;
    }
zsocket & cloudless::detail::zsocket::recv_buffer (int size)
Set kernel receive buffer size.
See 0MQ's documentation.
Parameters:
size the receive buffer size of the kernel.
Definition at line 428 of file zsocket.cpp.
References _M_setsockopt.
    {
        uint64v size_ = size;
        _M_setsockopt(ZMQ_RCVBUF, size_);
        return *this;
    }
int cloudless::detail::zsocket::recv_hwm () const
Get high water mark for inbound messages.
See 0MQ's documentation.
Returns:
high water mark for inbound messages.
Definition at line 316 of file zsocket.cpp.
References _M_getsockopt, and hwm().
    {
#if ZMQ_VERSION_MAJOR == 3
        int hwm_type = ZMQ_RCVHWM;
#elif ZMQ_VERSION_MAJOR == 2
        int hwm_type = ZMQ_HWM;
#endif
        uint64v hwm;
        _M_getsockopt(hwm_type, hwm);
        return hwm;
    }
zsocket & cloudless::detail::zsocket::recv_hwm (int hwm)
Set high water mark for inbound messages.
See 0MQ's documentation.
Parameters:
hwm high water mark for inbound messages.
Definition at line 496 of file zsocket.cpp.
References _M_setsockopt, and hwm().
    {
#if ZMQ_VERSION_MAJOR == 3
        int hwm_type = ZMQ_RCVHWM;
#elif ZMQ_VERSION_MAJOR == 2
        int hwm_type = ZMQ_HWM;
#endif
        uint64v hwm_ = hwm;
        _M_setsockopt(hwm_type, hwm_);
        return *this;
    }
bool cloudless::detail::zsocket::recv_more () const
Check if there are more message parts to follow while receiving a message.
See 0MQ's documentation.
Returns:
true or false.
Definition at line 216 of file zsocket.cpp.
References _M_getsockopt.
    {
        int64v more;
        _M_getsockopt(ZMQ_RCVMORE, more);
        return more;
    }
int cloudless::detail::zsocket::recv_timeout () const
Get maximum time before a receive operation times out.
See 0MQ's documentation.
Returns:
maximum time before a receive operation times out in milliseconds.
Definition at line 356 of file zsocket.cpp.
References _M_getsockopt.
    {
#if ZMQ_VERSION_MAJOR == 3
        int timeo;
        _M_getsockopt(ZMQ_RCVTIMEO, timeo);
        return timeo;
#elif ZMQ_VERSION_MAJOR == 2
        return _M_recvtimeo;
#endif
    }
zsocket & cloudless::detail::zsocket::recv_timeout (int timeout)
Set maximum time before a receive operation times out.
See 0MQ's documentation.
Parameters:
timeout maximum time before a receive operation times out in milliseconds.
Definition at line 530 of file zsocket.cpp.
References _M_setsockopt.
    {
        _M_recvtimeo = timeout;
#if ZMQ_VERSION_MAJOR == 3
        _M_setsockopt(ZMQ_RCVTIMEO, _M_recvtimeo);
#endif
        return *this;
    }
bool cloudless::detail::zsocket::recvmsg (zmessage & msg, int flags = 0)
Receive a message.
Parameters:
msg a reference to a zmessage instance.
flags receive flags to be passed to 0MQ's interface. See to 0MQ's documentation.
Returns:
whether the message was received successfully.
Definition at line 138 of file zsocket.cpp.
    {
        int rc = zmq_recvmsg(_Mp_socket, msg, flags);
#if ZMQ_VERSION_MAJOR == 3
        if (rc >= 0) // 0MQ 3.x returns the number of bytes received
            return true;
#elif ZMQ_VERSION_MAJOR == 2
        if (rc == 0)
            return true;
#endif
        if (rc == -1 && zmq_errno() == EAGAIN)
            return false;
        raise(zexception);
    }
int cloudless::detail::zsocket::send_buffer () const
Get kernel transmit buffer size.
See 0MQ's documentation.
Returns:
the transmit buffer size of the kernel.
Definition at line 198 of file zsocket.cpp.
References _M_getsockopt.
    {
        uint64v buffer;
        _M_getsockopt(ZMQ_SNDBUF, buffer);
        return buffer;
    }
zsocket & cloudless::detail::zsocket::send_buffer (int size)
Set kernel transmit buffer size.
See 0MQ's documentation.
Parameters:
size the transmit buffer size of the kernel.
Definition at line 419 of file zsocket.cpp.
References _M_setsockopt.
    {
        uint64v size_ = size;
        _M_setsockopt(ZMQ_SNDBUF, size_);
        return *this;
    }
int cloudless::detail::zsocket::send_hwm () const
Get high water mark for outbound messages.
See 0MQ's documentation.
Returns:
high water mark for outbound messages.
Definition at line 302 of file zsocket.cpp.
References _M_getsockopt, and hwm().
    {
#if ZMQ_VERSION_MAJOR == 3
        int hwm_type = ZMQ_SNDHWM;
#elif ZMQ_VERSION_MAJOR == 2
        int hwm_type = ZMQ_HWM;
#endif
        uint64v hwm;
        _M_getsockopt(hwm_type, hwm);
        return hwm;
    }
zsocket & cloudless::detail::zsocket::send_hwm (int hwm)
Set high water mark for outbound messages.
See 0MQ's documentation.
Parameters:
hwm high water mark for outbound messages.
Definition at line 482 of file zsocket.cpp.
References _M_setsockopt, and hwm().
    {
#if ZMQ_VERSION_MAJOR == 3
        int hwm_type = ZMQ_SNDHWM;
#elif ZMQ_VERSION_MAJOR == 2
        int hwm_type = ZMQ_HWM;
#endif
        uint64v hwm_ = hwm;
        _M_setsockopt(hwm_type, hwm_);
        return *this;
    }
int cloudless::detail::zsocket::send_timeout () const
Get maximum time before a send operation times out.
See 0MQ's documentation.
Returns:
maximum time before a send operation times out in milliseconds.
Definition at line 343 of file zsocket.cpp.
References _M_getsockopt.
    {
#if ZMQ_VERSION_MAJOR == 3
        int timeo;
        _M_getsockopt(ZMQ_SNDTIMEO, timeo);
        return timeo;
#elif ZMQ_VERSION_MAJOR == 2
        return _M_sendtimeo;
#endif
    }
zsocket & cloudless::detail::zsocket::send_timeout (int timeout)
Set maximum time before a send operation times out.
See 0MQ's documentation.
Parameters:
timeout maximum time before a send operation times out in milliseconds.
Definition at line 519 of file zsocket.cpp.
References _M_setsockopt.
    {
        _M_sendtimeo = timeout;
#if ZMQ_VERSION_MAJOR == 3
        _M_setsockopt(ZMQ_SNDTIMEO, _M_sendtimeo);
#endif
        return *this;
    }
bool cloudless::detail::zsocket::sendmsg (zmessage & msg, int flags = 0)
Send a message.
Parameters:
msg a reference to a zmessage instance.
flags send flags to be passed to 0MQ's interface. See to 0MQ's documentation.
Returns:
whether the message was sent successfully.
Definition at line 119 of file zsocket.cpp.
    {
        int rc = zmq_sendmsg(_Mp_socket, msg, flags);
#if ZMQ_VERSION_MAJOR == 3
        if (rc >= 0) // 0MQ 3.x returns the number of bytes sent
            return true;
#elif ZMQ_VERSION_MAJOR == 2
        if (rc == 0)
            return true;
#endif
        if (rc == -1 && zmq_errno() == EAGAIN)
            return false;
        raise(zexception);
    }
void cloudless::detail::zsocket::setsockopt (int option, const void * optval, size_t optvallen)
Set 0MQ socket options.
Parameters:
option a 0MQ socket option. See to 0MQ's documentation.
optval a pointer to the value of the option to be assigned.
optvallen the size of the container of the value.
Definition at line 81 of file zsocket.cpp.
    {
        int rc = zmq_setsockopt(_Mp_socket, option, optval, optvallen);
        if (rc == -1)
            raise(zexception);
    }
zsocket & cloudless::detail::zsocket::subscribe (const std::string & topic)
Subscribe to a topic on a SUB socket.
See 0MQ's documentation.
Parameters:
topic a topic to subscribe to.
Definition at line 552 of file zsocket.cpp.
References setsockopt(), and type().
    {
        if (type() != socket_type::SUB)
            raise(feature_not_supported);
        setsockopt(ZMQ_SUBSCRIBE, topic.c_str(), topic.size());
        return *this;
    }
int cloudless::detail::zsocket::type () const
Get this socket's type.
Returns:
a value matching one of the types in socket_types.
Definition at line 246 of file zsocket.cpp.
References _M_getsockopt.
    {
        int type;
        _M_getsockopt(ZMQ_TYPE, type);
        return type;
    }
zsocket & cloudless::detail::zsocket::unsubscribe (const std::string & topic)
Unsubscribe from a topic on a SUB socket.
See 0MQ's documentation.
Parameters:
topic a topic to unsubscribe from.
Definition at line 562 of file zsocket.cpp.
References setsockopt(), and type().
    {
        if (type() != socket_type::SUB)
            raise(feature_not_supported);
        setsockopt(ZMQ_UNSUBSCRIBE, topic.c_str(), topic.size());
        return *this;
    }
The documentation for this struct was generated from the following files:
cloudless/detail/zeromq/zsocket.hpp (c618bf69b5386ad87e90953f5f244252930f7399)
cloudless/detail/zeromq/zsocket.cpp (c618bf69b5386ad87e90953f5f244252930f7399)