Cloudless: cloudless::socket Struct Reference
cloudless::socket Struct Reference
A high level socket abstraction that wraps 0MQ's low level interface.
#include <socket.hpp>
Public Member Functions
socket (int type)
A constructor that takes a socket type.
socket (context &context, int type)
A constructor that takes a context and a socket type.
socket (detail::shared_ptr< context > context, int type)
A constructor that takes a context and a socket type.
socket & bind (const std::string &addr)
Bind this socket to a specific address given via a std::string.
socket & bind (const address &addr)
Bind this socket to a specific address given via the address structure.
socket & connect (const std::string &addr)
Connect this socket to a specific address given via a std::string.
socket & connect (const address &addr)
Connect this socket to a specific address given via the address structure.
virtual bool send (message &msg, bool block=true)
Send a message through this socket.
virtual bool recv (message &msg, bool block=true)
Receive a message through this socket.
pollitem & poll_item () throw ()
Get a pollitem that represents this socket.
Detailed Description
A high level socket abstraction that wraps 0MQ's low level interface.
Definition at line 49 of file socket.hpp.
Constructor & Destructor Documentation
cloudless::socket::socket (int type)
A constructor that takes a socket type.
and uses the global context.
Parameters:
type a socket type.
Definition at line 38 of file socket.cpp.
                           :
        detail::zsocket(*context::instance(), type)
    {
        _Mp_ip = detail::shared_ptr<pollitem>(new pollitem(*this));
    }
cloudless::socket::socket (context & context, int type)
A constructor that takes a context and a socket type.
Parameters:
context a context.
type a socket type.
Definition at line 44 of file socket.cpp.
                                             :
        detail::zsocket(context, type)
    {
        _Mp_ip = detail::shared_ptr<pollitem>(new pollitem(*this));
    }
cloudless::socket::socket (detail::shared_ptr< context > context, int type)
A constructor that takes a context and a socket type.
Parameters:
context a shared pointer of a context.
type a socket type.
Definition at line 50 of file socket.cpp.
                                                              :
        detail::zsocket(*context, type)
    {
        _Mp_ip = detail::shared_ptr<pollitem>(new pollitem(*this));
    }
Member Function Documentation
socket & cloudless::socket::bind (const std::string & addr)
Bind this socket to a specific address given via a std::string.
Parameters:
addr a socket address string.
Definition at line 57 of file socket.cpp.
    {
        detail::zsocket::bind(addr.c_str());
        return *this;
    }
socket & cloudless::socket::bind (const address & addr)
Bind this socket to a specific address given via the address structure.
Parameters:
addr a socket address structure.
Definition at line 65 of file socket.cpp.
References bind().
    {
        detail::zsocket::bind((const char*) addr);
        return *this;
    }
socket & cloudless::socket::connect (const std::string & addr)
Connect this socket to a specific address given via a std::string.
Parameters:
addr a socket address string.
Definition at line 73 of file socket.cpp.
    {
        detail::zsocket::connect(addr.c_str());
        return *this;
    }
socket & cloudless::socket::connect (const address & addr)
Connect this socket to a specific address given via the address structure.
Parameters:
addr a socket address structure.
Definition at line 81 of file socket.cpp.
References connect().
    {
        detail::zsocket::connect((const char*) addr);
        return *this;
    }
pollitem & cloudless::socket::poll_item () throw ()
Get a pollitem that represents this socket.
Returns:
a pollitem of this socket.
Definition at line 152 of file socket.cpp.
    {
        return *_Mp_ip;
    }
bool cloudless::socket::recv (message & msg, bool block = true) [virtual]
Receive a message through this socket.
Note that if a reference to a message with elements were to be passed, the message container will be cleared of all elements prior to filling it with the message to be received.
Parameters:
msg a reference to an instance of a message.
block whether to receive this message synchronously or asynchronously.
Returns:
whether the message was received successfully.
Reimplemented in cloudless::pub, and cloudless::push.
Definition at line 120 of file socket.cpp.
References cloudless::poller::add(), cloudless::detail::zsocket::can_recv(), cloudless::message::clear(), cloudless::poller::poll(), poll_item(), cloudless::message::push_tail(), cloudless::detail::zsocket::recv_more(), cloudless::detail::zsocket::recv_timeout(), cloudless::detail::zsocket::recvmsg(), cloudless::message::size(), and ZMQ_DONTWAIT.
    {
        if (msg.size())
            msg->clear();
#if ZMQ_VERSION_MAJOR == 2
        // An implementation for timed blocking.
        if (block && !can_recv()) {
            poller p;
            p.add("__recv_socket",
                    poll_item().register_event(poll_events::IN_EVENT));
            if (!p.poll(recv_timeout()) || !p["__recv_socket"].in())
                return false;
        }
#endif
        do {
            element e;
            if (!recvmsg(*e,
                        (block == true ? 0 : ZMQ_DONTWAIT)))
                return false;
            msg.push_tail(e);
        } while (recv_more());
        return true;
    }
bool cloudless::socket::send (message & msg, bool block = true) [virtual]
Send a message through this socket.
Parameters:
msg a reference to an instance of a message.
block whether to send this message synchronously or asynchronously.
Returns:
whether the message was sent successfully.
Reimplemented in cloudless::sub, and cloudless::pull.
Definition at line 89 of file socket.cpp.
References cloudless::poller::add(), cloudless::detail::zsocket::can_send(), cloudless::poller::poll(), poll_item(), cloudless::detail::zsocket::send_timeout(), cloudless::detail::zsocket::sendmsg(), cloudless::message::size(), and ZMQ_DONTWAIT.
    {
        if (msg->empty())
            raise(message_empty);
#if ZMQ_VERSION_MAJOR == 2
        // An implementation for timed blocking.
        if (block && !can_send()) {
            poller p;
            p.add("__send_socket",
                    poll_item().register_event(poll_events::OUT_EVENT));
            if (!p.poll(send_timeout()) || !p["__send_socket"].out())
                return false;
        }
#endif
        while (msg.size()) {
            if (!sendmsg(*msg->front(),
                        (msg->size() > 1 ? ZMQ_SNDMORE : 0)
                        | (block == true ? 0 : ZMQ_DONTWAIT)))
                return false;
            msg->pop_front();
        }
        return true;
    }
The documentation for this struct was generated from the following files:
cloudless/socket.hpp (05856d77e0dc496f5b6bfe16fdda38a037ac988a)
cloudless/socket.cpp (05856d77e0dc496f5b6bfe16fdda38a037ac988a)